### ISSUE TITLE
请求skillname_id_dict_{LMmodel_name}.npy

### ISSUE THREAD

**Issue by NousEU** [tubehao/SINKT#3]
请问我需要怎么去得到这个大模型预处理后的skillname_id_dict_{LMmodel_name}.npy文件？

**Comment by Vanquish6** [comment]
```
Traceback (most recent call last):
  File "/home/wjh/mamba/kt/SINKT/main.py", line 129, in <module>
    datasets, loaders = preprocess()
  File "/home/wjh/mamba/kt/SINKT/main.py", line 82, in preprocess
    with open(args.data_dir + 'problem_skill_maxSkillOfProblem_number.pkl', 'rb') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/SINKT/ass09/problem_skill_maxSkillOfProblem_number.pkl'
```

Hello 复现运行时报这个错误信息，请问可以提供一下problem_skill_maxSkillOfProblem_number.pkl文件吗？

**Comment by tubehao** [comment]
已上传
